services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api

    container_name: rag-api

    ports:
      - "8000:8000"

    env_file:
      - .env

    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit

    container_name: rag-streamlit

    ports:
      - "8501:8501"

    depends_on:
      - api

    env_file:
      - .env

    restart: unless-stopped

    